### PR TITLE
Iframepreview

### PR DESCRIPTION
**Pull request by agitator**
@MrTango would you have a look js iframe resizing, it doesn't do what I want ;-)

### CODE REVIEW

**Comment by gbastien** [comment]
Hi just my 2c but would you update https://github.com/collective/collective.js.iframeresizer instead and use it here?  We are going to use this package too.

+++

Gauthier

**Comment by MrTango** [comment]
@gbastien thx for the hint, it was a it to late for now, the work is done.
But i added an issue for doing this in the future: #117

**Comment by MrTango** [comment]
I fixed some issue with the Plone5 resources imports on Plone 4. Please always test also on Plone 4 if you have Plone 5 specific code.

**Comment by agitator** [comment]
i wasn't aware of collective.js.iframeresizer on the other hand the package doesn't seem to be ready for Plone 5
https://github.com/collective/collective.js.iframeresizer/blob/master/setup.py#L31

**Pull request merged**
